name: fluttercontactpicker
description: Use Androids' and iOS' native contact pickers to chose phone numbers and email addresses from contacts of the users address book
version: 3.1.1
homepage: https://github.com/DRSchlaubi/contact_picker/contact_picker

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.schlaubi.fluttercontactpicker
        pluginClass: FlutterContactPickerPlugin
      ios:
        pluginClass: FlutterContactPickerPlugin
